Added _pay_tomorrow.json.jbuilder file
nebulab/solidus_pay_tomorrow pull request #21
Opened 2022-11-24 08:51 UTC by abhishekgupta5

**Issue** - https://linear.app/nebulab-retainers/issue/ABU-27/the-shipments-tab-on-backend-isnt-showing-shipments

**Brief:**
We get a 500 in the api/orders/order-number network call because of the missing file and shipments are not shown in admin page. Adding this file fixes the issue

### Before
<img width="1469" alt="image" src="https://user-images.githubusercontent.com/9041163/203735849-bb4023a5-54fa-4646-a536-e6d8a7a85e57.png">

### After
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/9041163/203735960-20ad9efb-b46f-4925-bba4-4b3f09d64782.png">

2022-11-24 15:33 UTC, DanielePalombo requested changes
What do you think to add the source information to the json file?
We have done a similar thing on [solidus_bolt](https://github.com/solidusio/solidus_bolt/blob/751194a368b788dc3aa079adf689cb1f5188c630/app/views/spree/api/payments/source_views/_bolt.json.jbuilder)

2022-11-24 15:49 UTC, abhishekgupta5 commented
> What do you think to add the source information to the json file? We have done a similar thing on [solidus_bolt](https://github.com/solidusio/solidus_bolt/blob/751194a368b788dc3aa079adf689cb1f5188c630/app/views/spree/api/payments/source_views/_bolt.json.jbuilder)

What is the use of the info in this file in Bolt? I see it empty for [Viabill](https://github.com/nebulab/solidus_viabill/blob/main/app/views/spree/api/payments/source_views/_viabill.json.jbuilder) and [Acima](https://github.com/nebulab/solidus_acima/blob/master/app/views/spree/api/payments/source_views/_acima.json.jbuilder)

2022-11-24 16:08 UTC, DanielePalombo commented
> > What do you think to add the source information to the json file? We have done a similar thing on [solidus_bolt](https://github.com/solidusio/solidus_bolt/blob/751194a368b788dc3aa079adf689cb1f5188c630/app/views/spree/api/payments/source_views/_bolt.json.jbuilder)
> 
> What is the use of the info in this file in Bolt? I see it empty for [Viabill](https://github.com/nebulab/solidus_viabill/blob/main/app/views/spree/api/payments/source_views/_viabill.json.jbuilder) and [Acima](https://github.com/nebulab/solidus_acima/blob/master/app/views/spree/api/payments/source_views/_acima.json.jbuilder)

This is an API that should return source information when inquiried

2022-11-24 16:17 UTC, abhishekgupta5 commented
> > > What do you think to add the source information to the json file? We have done a similar thing on [solidus_bolt](https://github.com/solidusio/solidus_bolt/blob/751194a368b788dc3aa079adf689cb1f5188c630/app/views/spree/api/payments/source_views/_bolt.json.jbuilder)
> > 
> > 
> > What is the use of the info in this file in Bolt? I see it empty for [Viabill](https://github.com/nebulab/solidus_viabill/blob/main/app/views/spree/api/payments/source_views/_viabill.json.jbuilder) and [Acima](https://github.com/nebulab/solidus_acima/blob/master/app/views/spree/api/payments/source_views/_acima.json.jbuilder)
> 
> This is an API that should return source information when inquiried

Added in https://github.com/nebulab/solidus_pay_tomorrow/pull/21/commits/6a0518f895470cd9b377072c42a5e28dccc1efbc

2022-11-25 17:20 UTC, DanielePalombo approved these changes

2022-11-25 17:28 UTC, merged